// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmemylmcbmrieheutktb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtZW15bG1jYm1yaWVoZXV0a3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTc3NTcsImV4cCI6MjA2NDAzMzc1N30.HNxI8Os1UggwawOzRNV7kjPPDOj9xmfAYtDsfiQdLEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);